language: swift
osx_image: xcode9.2

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild -project TreinamentoIOS.xcodeproj -scheme TreinamentoIOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

